"use client";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {useState,useTransition} from "react";
import {CalendarDays,ChevronLeft,ChevronRight,Clock3,Pencil,Plus,X} from "lucide-react";
import {requestExtraHours,requestShiftChange} from "./actions";
type Shift={id:number;entry_type:string;shift_date:string;start_time:string;end_time:string;notes:string|null;approval_status:"pending"|"approved"|"rejected"};
type Request={id:number;work_shift_id:number|null;request_type:"add_extra"|"change_shift";proposed_date:string;proposed_start_time:string;proposed_end_time:string;status:string};
const DAYS=["Lunedì","Martedì","Mercoledì","Giovedì","Venerdì","Sabato","Domenica"],LABELS:Record<string,string>={work:"Turno",extra:"Ore extra",rol:"ROL",holiday:"Ferie",sick:"Malattia"};
function addDays(value:string,days:number){const date=new Date(`${value}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10)}
function dateLabel(value:string){return new Intl.DateTimeFormat("it-IT",{day:"2-digit",month:"short",timeZone:"UTC"}).format(new Date(`${value}T12:00:00Z`))}
export function EmployeeShifts({name,weekStart,minWeek,shifts,requests}:{name:string;weekStart:string;minWeek:string;shifts:Shift[];requests:Request[]}){
 const router=useRouter(),[extraOpen,setExtraOpen]=useState(false),[editing,setEditing]=useState<Shift|null>(null),[error,setError]=useState(""),[pending,startTransition]=useTransition();const today=new Date().toISOString().slice(0,10);const days=DAYS.map((name,index)=>({name,date:addDays(weekStart,index)}));
 function run(action:(data:FormData)=>Promise<{ok:boolean;error?:string}>,data:FormData,close:()=>void){setError("");startTransition(async()=>{const result=await action(data);if(!result.ok){setError(result.error??"Operazione non riuscita.");return}close();router.refresh()})}
 return <main className="admin-container employee-portal"><header className="employee-portal-heading"><div><p className="admin-kicker">Area personale</p><h1>I miei turni</h1><p>Ciao {name}. Consulta la pianificazione e comunica aggiunte o variazioni.</p></div><button className="admin-action admin-action-primary admin-action-create" onClick={()=>setExtraOpen(true)}><Plus size={17}/> Aggiungi ore extra</button></header>{error&&<div className="staff-alert"><span>{error}</span><button onClick={()=>setError("")}><X size={16}/></button></div>}<section className="employee-week-toolbar"><Link className={weekStart<=minWeek?"is-disabled":""} aria-disabled={weekStart<=minWeek} href={weekStart<=minWeek?`/admin/i-miei-turni?week=${weekStart}`:`/admin/i-miei-turni?week=${addDays(weekStart,-7)}`}><ChevronLeft/></Link><div><CalendarDays/><span><small>Settimana</small><strong>{dateLabel(weekStart)} – {dateLabel(addDays(weekStart,6))}</strong></span></div><Link href={`/admin/i-miei-turni?week=${addDays(weekStart,7)}`}><ChevronRight/></Link></section>
 <section className="employee-week-grid">{days.map(day=>{const rows=shifts.filter(s=>s.shift_date===day.date),added=requests.filter(r=>r.request_type==="add_extra"&&r.proposed_date===day.date);return <article key={day.date} className="employee-day-card"><header><span>{day.name}</span><strong>{dateLabel(day.date)}</strong></header><div>{rows.map(shift=>{const change=requests.find(r=>r.work_shift_id===shift.id);return <button key={shift.id} className={`employee-shift-row${change?" has-request":""}`} disabled={shift.shift_date<today||Boolean(change)} onClick={()=>setEditing(shift)}><i/><div><strong>{LABELS[shift.entry_type]??shift.entry_type}</strong><span><Clock3 size={13}/>{shift.start_time.slice(0,5)} – {shift.end_time.slice(0,5)}</span>{change&&<em>Modifica in attesa</em>}</div>{!change&&shift.shift_date>=today&&<Pencil size={13}/>}</button>})}{added.map(r=><section key={r.id} className="employee-shift-row has-request"><i/><div><strong>Ore extra richieste</strong><span><Clock3 size={13}/>{r.proposed_start_time.slice(0,5)} – {r.proposed_end_time.slice(0,5)}</span><em>In attesa</em></div></section>)}{!rows.length&&!added.length&&<p>Nessun turno</p>}</div></article>})}</section>
 {extraOpen&&<RequestModal title="Aggiungi ore extra" pending={pending} onClose={()=>setExtraOpen(false)} onSubmit={data=>run(requestExtraHours,data,()=>setExtraOpen(false))}/>} {editing&&<RequestModal title="Richiedi modifica turno" pending={pending} shift={editing} onClose={()=>setEditing(null)} onSubmit={data=>{data.set("shift_id",String(editing.id));run(requestShiftChange,data,()=>setEditing(null))}}/>}</main>
}
function RequestModal({title,pending,shift,onClose,onSubmit}:{title:string;pending:boolean;shift?:Shift;onClose:()=>void;onSubmit:(data:FormData)=>void}){return <div className="admin-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!pending)onClose()}}><section className="admin-modal"><button className="modal-close" onClick={onClose}><X/></button><p className="admin-kicker">Richiesta dipendente</p><h2>{title}</h2><p className="employee-extra-intro">La variazione sarà applicata solo dopo l’approvazione dell’amministratore.</p><form className="admin-edit-grid" onSubmit={e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget))}}><label className="admin-field admin-field-wide"><span>Giorno</span><input name="shift_date" type="date" min={new Date().toISOString().slice(0,10)} defaultValue={shift?.shift_date} required/></label><label className="admin-field"><span>Inizio</span><input name="start_time" type="time" step="900" defaultValue={shift?.start_time.slice(0,5)} required/></label><label className="admin-field"><span>Fine</span><input name="end_time" type="time" step="900" defaultValue={shift?.end_time.slice(0,5)} required/></label><label className="admin-field admin-field-wide"><span>Motivo / note</span><textarea name="notes" rows={3}/></label><div className="modal-actions admin-field-wide"><button type="button" className="admin-action admin-action-secondary" onClick={onClose}>Annulla</button><button className="admin-action admin-action-primary" disabled={pending}>{pending?"Invio…":"Invia richiesta"}</button></div></form></section></div>}
